get-scripts:
	curl https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.4.4/babel.min.js -o babel.js
	curl https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.3.14/polyfill.min.js -o polyfill.js
